### PR TITLE
Made ratingConditionsHaveBeenMet() public.

### PR DESCRIPTION
**Pull request by bjaskj**
Extract of #27, but with only ratingConditionsHaveBeenMet() made public.

We have a need to get this information in several apps.

### CODE REVIEW

**Comment by coneybeare** [comment]
I'll merge this no prob. Can you please also update the `Readme` to introduce this newly public method?

**Comment by bjaskj** [comment]
I have updated readme.

**Comment by coneybeare** [comment]
Thanks!

**Comment by brownpixel** [comment]
Its no longer public in current version

**Pull request merged**
