### PR TITLE
Fix localization by getting the framework bundle

### PR DESCRIPTION
**Pull request by phimage**
I use compiled framework (with cocoapod or carthage)
Localization does'nt work because main bundle is used (there is no .bundle)
So the fix allow to use the correct framework bundle

### CODE REVIEW

**Comment by coneybeare** [comment]
Have you tested this change out on a cocoapods installation, carthage installation and the example project?

**Comment by phimage** [comment]
Cocoapod and Carthage
(And its a well know issue done when using nsbundle, in unit test for instance)

I update only the case when you don't know what to return.
The case '.bundle' file exists is prioritary and not changed
and to use main bundle there is a property

I can launch example app next week if you want

**Comment by coneybeare** [comment]
Not well known to me, so I need to know it works for all cases, and is backwards compatible with all supported versions or Armchair before I merge it in.

**Comment by phimage** [comment]
tested with demo apps and as I guess without testing the code that I modify is never called
 only the `bundle` one for normal prompt
```
if let url = armchairBundleURL {
     bundle = NSBundle(URL: url)	
}
```
and `useMainAppBundleForLocalizations`for custom prompt

the third case that I modify is "no bundle file" and no `useMainAppBundleForLocalizations` and "say" use the `NSBundle` near the current class

**Comment by coneybeare** [comment]
will `NSBundle.mainBundle()` return nil for you the way you have your setup? If so, this would be better written as a third clause instead of replacing it. You could `let` the `mainBundle` then if that fails, go to the 
`dynamicType` case.

**Comment by phimage** [comment]
`NSBundle.mainBundle()` never return `nil`. (For a framework is just not the good bundle)
`NSBundle(forClass:` never failed too and can be the main bundle if class (here `ArmSwift`) is compiled in the application (not in a separated framework)

**Pull request merged**
