### PR TITLE
Update to Swift 5

### PR DESCRIPTION
**Pull request by weakfl**
- convert all targets to Swift 5
- bump `.swift-version`
- update podspec
- fix warnings
- update projects to recommended settings

```
% pod lib lint

 -> Armchair (0.3.6)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')

Armchair passed validation.
```

### CODE REVIEW

**Comment by dfmuir** [comment]
I would also like to see this implemented. I am seeing a warning in my Swift 5 project that integrates Armchair.

**Comment by weakfl** [comment]
Thanks for merging @coneybeare. Could you please also make a new release and push to trunk?

**Comment by coneybeare** [comment]
Done. 0.3.7

**Review by DrDimasBeste — COMMENTED** [review]
](

**Comment by DrDimasBeste** [comment]
> Done. 0.3.7

**Pull request merged**
