### PR TITLE
Fixing errors and warning when using Swift 2

### PR DESCRIPTION
**Pull request by gershwin88**
I updated Armchair.swift to fix the errors and warnings created when converting to Swift 2 from 1.2

### CODE REVIEW

**Comment by helgetan** [comment]
works for me, pls pull

**Comment by coneybeare** [comment]
Thanks!

**Comment by fabdarice** [comment]
Hi @gershwin88  @coneybeare 
Ever since updating to the new Armchair for Swift 2.0, I cannot seem to make Armchair pop-up appear.
I don't see any errors message and everything is compiling perfectly.
Even if I add : Armchair.debugEnabled(true) in my initialize function in AppDelegate, I don't see the pop-up.

**Comment by coneybeare** [comment]
Stepping through the code, there was an issue in the `connectedToInternet` method and Swift 2, so I replaced it.

**Comment by fabdarice** [comment]
Thank you @coneybeare for your prompt reaction! Now, it displays correctly the pop-up.
However, it seems like for device with ios < 9, when you click on "Rate", it displays a white screen, while in ios 9, it redirects you correctly on the app store for the app.
Any idea why? I've tried on 2 ios 8 devices and one ios 9 device

**Comment by fabdarice** [comment]
storeViewController.loadProductWithParameters(productParameters, completionBlock: {(success: Bool,error: NSError?) -> Void in
     print(error)
     print(success)
})

Even after presenting the view, I never reach the completionBlock in device with ios < 9. It works fine in device > 9.

Any idea??

**Pull request merged**
